### ISSUE TITLE
GrijjyLogBroker.exe has virus "IDP.Generic" by Avast pro Antivirus

### ISSUE THREAD

**Issue by romanvitek** [grijjy/GrijjyCloudLogger#5]
Hi, my Avast Pro Antivirus move the GrijjyLogBroker.exe do "virus safe" with info about  virus "IDP.Generic".

I there any other option to compile this module ?

Thaks, Rovi

**Comment by grijjy** [comment]
Thank you for taking the time to try the Grijjy Cloud Logger.  At this time, there are no viruses in the cloud logger.  This is a false positive report from your Avast anti-virus software.  We don't currently provide the source to the logger because it depends on various other units and classes we have not yet released to the foundation.
